apiVersion: v1
kind: Secret
metadata:
  name: vehicle-sales-secret
  namespace: vehicle-platform
type: Opaque
stringData:
  DATABASE_URL: postgresql://sales_user:sales_password@postgres-sales:5432/sales_db
  INTERNAL_SERVICE_TOKEN: replace-me-internal
